; generated by Component: ARM Compiler 5.04 update 1 (build 49) Tool: ArmCC [5040049]
; commandline ArmCC [--c99 --debug -c --asm -o.\objs\irqs.o --depend=.\objs\irqs.d --apcs=interwork -Otime --diag_suppress=9931 -IC:\Keil\ARM\INC\Phillips -I..\SharedCode -IC:\Keil_v5\ARM\RV31\INC -IC:\Keil_v5\ARM\CMSIS\Include -IC:\Keil_v5\ARM\Inc\Philips --enum_is_int --omf_browse=.\objs\irqs.crf irqs.c]
        ARM
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

init_VIC PROC
        MOV      r0,#0
        PUSH     {r4,r5}
        MVN      r1,#0
        MOV      r3,r0
        STR      r1,[r0,#-0xfec]
        STR      r0,[r0,#-0x100]
        STR      r0,[r0,#-0xff4]
        SUB      r5,r0,#0xf00
        SUB      r4,r0,#0xe00
        MOV      r12,#0xf
|L1.40|
        STR      r3,[r5,r0,LSL #2]
        STR      r12,[r4,r0,LSL #2]
        ADD      r0,r0,#1
        CMP      r0,#0x20
        BCC      |L1.40|
        POP      {r4,r5}
        BX       lr
        ENDP

install_irq PROC
        MOV      r3,#1
        PUSH     {r4,r5}
        LSL      r3,r3,r0
        MOV      r4,#0
        STR      r3,[r4,#-0xfec]
        CMP      r0,#0x20
        POPCS    {r4,r5}
        MOVCS    r0,#0
        BXCS     lr
        MOV      r12,#0xf100
        SUB      r12,r12,#0x10000
        ADD      r12,r12,r0,LSL #2
        MOV      r5,#0xf200
        SUB      r5,r5,#0x10000
        STR      r1,[r12,#0]
        STR      r2,[r5,r0,LSL #2]
        STR      r3,[r4,#-0xff0]
        POP      {r4,r5}
        MOV      r0,#1
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT init_VIC [CODE]
        EXPORT install_irq [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,2
        ATTR SETVALUE Tag_ABI_optimization_goals,2
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
