; generated by Component: ARM Compiler 5.04 update 1 (build 49) Tool: ArmCC [5040049]
; commandline ArmCC [--c99 --debug -c --asm -o.\objs\pll.o --depend=.\objs\pll.d --apcs=interwork -Otime --diag_suppress=9931 -IC:\Keil\ARM\INC\Phillips -I..\SharedCode -IC:\Keil_v5\ARM\RV31\INC -IC:\Keil_v5\ARM\CMSIS\Include -IC:\Keil_v5\ARM\Inc\Philips --enum_is_int --omf_browse=.\objs\pll.crf PLL.c]
        ARM
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

PLL_CLOCK_SETUP PROC
        MOV      r1,#0x1fc000
        CMP      r0,#0
        ADD      r1,r1,#0xe0000000
        BEQ      |L1.160|
        LDR      r2,[r1,#0x1a8]
        CMP      r0,#1
        BIC      r2,r2,#0xc0
        STR      r2,[r1,#0x1a8]
        LDR      r2,[r1,#0x1a8]
        BEQ      |L1.212|
        ORR      r2,r2,#0x3000000
        ORR      r2,r2,#0x280
        STR      r2,[r1,#0x1a8]
        LDR      r2,[r1,#0x1ac]
        BIC      r2,r2,#0xf0000
        STR      r2,[r1,#0x1ac]
        LDR      r2,[r1,#0x1ac]
        ORR      r2,r2,#0xa0000
        STR      r2,[r1,#0x1ac]
|L1.76|
        MOV      r2,#1
        STR      r2,[r1,#0x10c]
        MOV      r2,#0x4b
        ADD      r2,r2,#0x10000
        STR      r2,[r1,#0x84]
        MOV      r12,#0xaa
        STR      r12,[r1,#0x8c]
        MOV      r3,#0x55
        STR      r3,[r1,#0x8c]
        CMP      r0,#0
        MOV      r2,#7
        BEQ      |L1.140|
        CMP      r0,#1
        MOVEQ    r2,#3
        STREQ    r2,[r1,#0x104]
        BEQ      |L1.144|
|L1.140|
        STR      r2,[r1,#0x104]
|L1.144|
        LDR      r2,[r1,#0x88]
        TST      r2,#0x4000000
        BNE      |L1.268|
        B        |L1.252|
|L1.160|
        LDR      r2,[r1,#0x1a8]
        BIC      r2,r2,#0xc0
        STR      r2,[r1,#0x1a8]
        LDR      r2,[r1,#0x1a8]
        ORR      r2,r2,#0x100000
        ORR      r2,r2,#0x140
        STR      r2,[r1,#0x1a8]
        LDR      r2,[r1,#0x1ac]
        BIC      r2,r2,#0xf0000
        STR      r2,[r1,#0x1ac]
        LDR      r2,[r1,#0x1ac]
        ORR      r2,r2,#0x50000
        B        |L1.244|
|L1.212|
        ORR      r2,r2,#0x3200000
        ORR      r2,r2,#0x280
        STR      r2,[r1,#0x1a8]
        LDR      r2,[r1,#0x1ac]
        BIC      r2,r2,#0xf0000
        STR      r2,[r1,#0x1ac]
        LDR      r2,[r1,#0x1ac]
        ORR      r2,r2,#0xa0000
|L1.244|
        STR      r2,[r1,#0x1ac]
        B        |L1.76|
|L1.252|
        MOV      r0,r0
        LDR      r2,[r1,#0x88]
        TST      r2,#0x4000000
        BEQ      |L1.252|
|L1.268|
        STR      r12,[r1,#0x8c]
        STR      r3,[r1,#0x8c]
        CMP      r0,#0
        CMPNE    r0,#1
        BXNE     lr
        LDR      r0,[r1,#0xc4]
        ORR      r0,r0,#0x3000000
        ORR      r0,r0,#0x1000
        ORR      r0,r0,#0x1e
        STR      r0,[r1,#0xc4]
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT PLL_CLOCK_SETUP [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,2
        ATTR SETVALUE Tag_ABI_optimization_goals,2
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
