; generated by Component: ARM Compiler 5.04 update 1 (build 49) Tool: ArmCC [5040049]
; commandline ArmCC [--c99 --debug -c --asm -o.\objs\radar.o --depend=.\objs\radar.d --apcs=interwork -Otime --diag_suppress=9931 -IC:\Keil\ARM\INC\Phillips -I..\SharedCode -IC:\Keil_v5\ARM\RV31\INC -IC:\Keil_v5\ARM\CMSIS\Include -IC:\Keil_v5\ARM\Inc\Philips --enum_is_int --omf_browse=.\objs\radar.crf radar.c]
        ARM
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

        REQUIRE _printf_percent
        REQUIRE _printf_d
        REQUIRE _printf_int_dec
        REQUIRE _printf_x
        REQUIRE _printf_longlong_hex
initRadar PROC
        PUSH     {r3-r5,lr}
        LDR      r0,|L1.648|
        MOV      r1,#0x288
        BL       __aeabi_memclr4
        MOV      r2,#1
        MOV      r1,sp
        MOV      r0,#0x25
        BL       readFramData
        LDRB     r0,[sp,#0]
        LDR      r4,|L1.648|
        MOV      r2,#4
        CMP      r0,#0xa
        MOVHI    r0,#3
        STRB     r0,[r4,#0x27c]  ; radarInfo
        MOV      r1,sp
        MOV      r0,#0x26
        BL       readFramData
        LDRB     r0,[sp,#0]
        LDRB     r1,[sp,#3]
        LDRB     r2,[sp,#1]
        ORR      r0,r0,r1,LSL #24
        LDRB     r1,[sp,#2]
        LSL      r1,r1,#16
        ORR      r1,r1,r2,LSL #8
        ORR      r0,r0,r1
        STR      r0,[r4,#0x280]  ; radarInfo
        LDR      r1,|L1.652|
        SUB      r0,r0,#0x800
        SUB      r0,r0,#0x3b8
        CMP      r0,r1
        MOVCS    r0,#0xa60
        ADDCS    r0,r0,#0xe000
        STRCS    r0,[r4,#0x280]  ; radarInfo
        POP      {r3-r5,lr}
        BX       lr
        ENDP

buildRxRadarPacket PROC
        PUSH     {r4-r9,lr}
        MOV      r6,r0
        LDRSH    r0,[r2,#0]
        LDR      r7,|L1.656|
        SUB      sp,sp,#0x14
        CMN      r0,#1
        LDRBEQ   r0,[r7,#0]  ; packetError
        MOV      r5,r2
        MOV      r4,r1
        CMPEQ    r0,#0
        MOV      r9,#0
        BNE      |L1.200|
        STRH     r9,[r5,#0]
        BL       getTimeNow
        STR      r0,[r7,#4]  ; packetTimeStamp
|L1.200|
        LDRSH    r0,[r5,#0]
        LDR      r2,|L1.648|
        MOV      r8,#1
        STRB     r6,[r4,r0]
        LDRH     r0,[r5,#0]
        MVN      r6,#0
        ADD      r0,r0,#1
        STRH     r0,[r5,#0]
        LDRB     r0,[r2,#0x284]  ; radarInfo
        BIC      r0,r0,#3
        STRB     r0,[r2,#0x284]  ; radarInfo
        LDRSH    r1,[r5,#0]
        CMP      r1,#7
        BLE      |L1.284|
        ADR      r0,|L1.660|
        BL       __2printf
        STRH     r6,[r5,#0]
        STRB     r8,[r7,#0]  ; packetError
        ADD      sp,sp,#0x14
        POP      {r4-r9,lr}
        BX       lr
|L1.284|
        LDRB     r0,[r7,#0]  ; packetError
        CMP      r0,#0
        BEQ      |L1.400|
        SUB      r0,r4,#1
        LDRB     r0,[r1,r0]
        CMP      r0,#3
        ADDNE    sp,sp,#0x14
        POPNE    {r4-r9,lr}
        BXNE     lr
        SUB      r0,r4,#2
        LDRB     r0,[r1,r0]
        CMP      r0,#0xaa
        ADDNE    sp,sp,#0x14
        POPNE    {r4-r9,lr}
        BXNE     lr
        SUB      r0,r4,#3
        LDRB     r0,[r1,r0]
        CMP      r0,#1
        ADDNE    sp,sp,#0x14
        POPNE    {r4-r9,lr}
        BXNE     lr
        STRH     r6,[r5,#0]
        STRB     r9,[r7,#0]  ; packetError
        BL       getTimeNow
        ADD      sp,sp,#0x14
        POP      {r4-r9,lr}
        MOV      r1,r0
        ADR      r0,|L1.692|
        B        __2printf
|L1.400|
        CMP      r1,#7
        BGE      |L1.496|
        CMP      r1,#3
        ADDLE    sp,sp,#0x14
        POPLE    {r4-r9,lr}
        BXLE     lr
        LDRB     r1,[r4,#0]
        CMP      r1,#2
        LDRBEQ   r0,[r4,#1]
        CMPEQ    r0,#0x84
        LDRBEQ   r0,[r4,#2]
        CMPEQ    r0,#1
        ADDEQ    sp,sp,#0x14
        POPEQ    {r4-r9,lr}
        BXEQ     lr
        LDRB     r3,[r4,#2]
        LDRB     r2,[r4,#1]
        ADR      r0,|L1.716|
        BL       __2printf
        STRH     r6,[r5,#0]
        STRB     r8,[r7,#0]  ; packetError
        ADD      sp,sp,#0x14
        POP      {r4-r9,lr}
        BX       lr
|L1.496|
        LDRB     r0,[r4,#4]
        CMP      r0,#1
        LDRBEQ   r1,[r4,#5]
        CMPEQ    r1,#0xaa
        LDRBEQ   r1,[r4,#6]
        CMPEQ    r1,#3
        BEQ      |L1.588|
        LDRB     r2,[r4,#5]
        LDRB     r1,[r4,#6]
        LDRB     r3,[r4,#3]
        STMIB    sp,{r0,r2}
        STR      r1,[sp,#0xc]
        STR      r3,[sp,#0]
        LDRB     r3,[r4,#2]
        LDRB     r2,[r4,#1]
        LDRB     r1,[r4,#0]
        ADR      r0,|L1.752|
        BL       __2printf
        STRH     r6,[r5,#0]
        STRB     r8,[r7,#0]  ; packetError
        ADD      sp,sp,#0x14
        POP      {r4-r9,lr}
        BX       lr
|L1.588|
        LDRB     r1,[r4,#3]
        LDRB     r0,[r2,#0x27c]  ; radarInfo
        CMP      r1,r0
        LDR      r0,|L1.812|
        MOVLS    r1,#0
        LDRH     r3,[r0,#0]  ; radarInfo
        STRB     r1,[r2,r3]
        LDRH     r1,[r0,#0]  ; radarInfo
        ADD      r1,r1,#1
        BIC      r1,r1,#0xfe00
        STRH     r1,[r0,#0]  ; radarInfo
        STRH     r6,[r5,#0]
        ADD      sp,sp,#0x14
        POP      {r4-r9,lr}
        BX       lr
|L1.648|
        DCD      ||.bss||
|L1.652|
        DCD      0x00091c09
|L1.656|
        DCD      ||.data||
|L1.660|
        DCB      "\r\nRadar PACKET ERROR OV %d\n\r",0
        DCB      0
        DCB      0
        DCB      0
|L1.692|
        DCB      "\r\nRadar Re-Sync  <%d>\n\r",0
|L1.716|
        DCB      "\r\nRadar SYNC ERR 0x%X 0x%X 0x%X\n\r",0
        DCB      0
        DCB      0
|L1.752|
        DCB      "\r\nRadar TRAIL ERR [0x%X 0x%X 0x%X 0x%X 0x%X 0x%X 0x%X"
        DCB      "]\n\r",0
        DCB      0
        DCB      0
        DCB      0
|L1.812|
        DCD      ||.bss||+0x200
        ENDP

calcAvgSpeed PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        LDR      r0,|L1.812|
        MOV      r6,r1
        LDRH     r12,[r0,#0]  ; radarInfo
        LDR      r1,|L1.648|
        MOV      r3,#0
        SUB      r0,r12,r6
        LSL      r2,r0,#23
        MOV      r4,r3
        LSR      r2,r2,#23
|L1.860|
        LDRB     r0,[r1,r2]
        CMP      r0,#0
        ADDNE    r3,r3,r0
        ADD      r0,r2,#1
        ADDNE    r4,r4,#1
        BIC      r2,r0,#0xfe00
        CMP      r12,r2
        BNE      |L1.860|
        LSR      r0,r4,#8
        STRB     r4,[r5,#4]
        CMP      r4,#0
        STRB     r0,[r5,#5]
        MOVEQ    r0,#0
        STRBEQ   r0,[r5,#0]
        BEQ      |L1.952|
        MOV      r1,r4
        MOV      r0,r3
        BL       __aeabi_uidivmod
        STRB     r0,[r5,#0]
        MOV      r0,#0x64
        MUL      r0,r4,r0
        MOV      r1,r6
        BL       __aeabi_uidivmod
|L1.952|
        STRB     r0,[r5,#1]
        LSR      r0,r6,#8
        STRB     r6,[r5,#2]
        STRB     r0,[r5,#3]
        POP      {r4-r6,lr}
        BX       lr
        ENDP

radarDoWork PROC
        PUSH     {r4,r5,lr}
        LDR      r0,|L1.656|
        MOV      r1,#0x770
        LDR      r0,[r0,#4]  ; packetTimeStamp
        SUB      sp,sp,#0xc
        ADD      r1,r1,#0x1000
        BL       hasTimedOut
        LDR      r4,|L1.648|
        CMP      r0,#0
        BEQ      |L1.1076|
        LDRB     r0,[r4,#0x284]  ; radarInfo
        TST      r0,#2
        ADDNE    sp,sp,#0xc
        POPNE    {r4,r5,lr}
        BXNE     lr
        BL       getTimeNow
        MOV      r1,r0
        ADR      r0,|L1.1976|
        BL       __2printf
        LDRB     r0,[r4,#0x284]  ; radarInfo
        ORR      r0,r0,#3
        STRB     r0,[r4,#0x284]  ; radarInfo
        ADD      sp,sp,#0xc
        POP      {r4,r5,lr}
        BX       lr
|L1.1076|
        MOV      r1,#0x710
        LDR      r0,[r4,#0x278]  ; radarInfo
        ADD      r1,r1,#0x2000
        BL       hasTimedOut
        CMP      r0,#0
        ADDEQ    sp,sp,#0xc
        POPEQ    {r4,r5,lr}
        BXEQ     lr
        LDR      r0,[r4,#0x280]  ; radarInfo
        MOV      r1,#0x6e
        ADD      r1,r1,#0x100
        MUL      r0,r1,r0
        LDR      r1,|L1.2016|
        UMULL    r2,r0,r1,r0
        LSR      r0,r0,#14
        BIC      r1,r0,#0x30000
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r0,[sp,#0]
        STRB     r0,[r4,#0x202]
        LDRH     r1,[sp,#4]
        ADD      r0,r4,#0x200
        STRH     r1,[r0,#6]
        LDRH     r1,[sp,#2]
        STRH     r1,[r0,#4]
        LDRB     r0,[sp,#1]
        STRB     r0,[r4,#0x203]
        BL       getTimeNow
        STR      r0,[r4,#0x24c]
        MOV      r1,#0x1ac
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x208]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#6
        ADD      r1,r1,#0x200
        ADD      r1,r1,#6
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x250]
        MOV      r1,#0x82
        ADD      r1,r1,#0x100
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r1,[sp,#0]
        LDR      r0,|L1.648|
        STRB     r1,[r0,#0x20e]
        LDRH     r1,[sp,#4]
        ADD      r4,r0,#0xc
        ADD      r0,r0,#0x20c
        STRH     r1,[r0,#6]
        LDRH     r1,[sp,#2]
        STRH     r1,[r0,#4]
        LDRB     r0,[sp,#1]
        STRB     r0,[r4,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x254]
        MOV      r1,#0x57
        ADD      r1,r1,#0x100
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x214]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x12
        ADD      r1,r1,#0x200
        ADD      r1,r1,#0x12
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        STR      r0,[r4,#0x24c]
        MOV      r1,#0x12c
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r1,[sp,#0]
        LDR      r0,|L1.648|
        STRB     r1,[r0,#0x21a]
        LDRH     r1,[sp,#4]
        ADD      r5,r0,#0x18
        ADD      r0,r0,#0x218
        STRH     r1,[r0,#6]
        LDRH     r1,[sp,#2]
        STRH     r1,[r0,#4]
        LDRB     r0,[sp,#1]
        STRB     r0,[r5,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x25c]
        MOV      r1,#1
        ADD      r1,r1,#0x100
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x220]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x1e
        ADD      r1,r1,#0x200
        ADD      r1,r1,#0x1e
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x260]
        MOV      r1,#0xd6
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r1,[sp,#0]
        LDR      r0,|L1.648|
        STRB     r1,[r0,#0x226]
        LDRH     r1,[sp,#4]
        ADD      r4,r0,#0x24
        ADD      r0,r0,#0x224
        STRH     r1,[r0,#6]
        LDRH     r1,[sp,#2]
        STRH     r1,[r0,#4]
        LDRB     r0,[sp,#1]
        STRB     r0,[r4,#0x203]
        BL       getTimeNow
        STR      r0,[r5,#0x24c]
        MOV      r1,#0xab
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x22c]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x2a
        ADD      r1,r1,#0x200
        ADD      r1,r1,#0x2a
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x268]
        MOV      r1,#0x80
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x232]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x30
        ADD      r1,r1,#0x230
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x26c]
        MOV      r1,#0x55
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x238]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x36
        ADD      r1,r1,#0x200
        ADD      r1,r1,#0x36
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        STR      r0,[r4,#0x24c]
        MOV      r1,#0x2a
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x23e]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x3c
        ADD      r1,r1,#0x23c
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x274]
        MOV      r1,#0xe
        MOV      r0,sp
        BL       calcAvgSpeed
        LDRB     r2,[sp,#0]
        LDR      r1,|L1.648|
        STRB     r2,[r1,#0x244]
        LDRH     r2,[sp,#4]
        ADD      r0,r1,#0x42
        ADD      r1,r1,#0x200
        ADD      r1,r1,#0x42
        STRH     r2,[r1,#6]
        LDRH     r2,[sp,#2]
        STRH     r2,[r1,#4]
        LDRB     r1,[sp,#1]
        STRB     r1,[r0,#0x203]
        BL       getTimeNow
        LDR      r1,|L1.648|
        STR      r0,[r1,#0x278]
        ADD      sp,sp,#0xc
        POP      {r4,r5,lr}
        BX       lr
|L1.1976|
        DCB      "\r\nRadar tracker PACKET TIME OUT  <%d>\n\r",0
|L1.2016|
        DCD      0x10624dd3
        ENDP

getAvgSpeed PROC
        LDR      r1,|L1.648|
        ADD      r0,r0,r0,LSL #1
        ADD      r0,r1,r0,LSL #1
        LDRB     r0,[r0,#0x202]
        BX       lr
        ENDP

getTotalRadarReadings PROC
        LDR      r1,|L1.648|
        ADD      r0,r0,r0,LSL #1
        ADD      r0,r1,r0,LSL #1
        LDRB     r0,[r0,#0x204]
        BX       lr
        ENDP

getNonZeroRadarReadings PROC
        LDR      r1,|L1.648|
        ADD      r0,r0,r0,LSL #1
        ADD      r0,r1,r0,LSL #1
        LDRB     r0,[r0,#0x206]
        BX       lr
        ENDP

getOccupancyPercent PROC
        LDR      r1,|L1.648|
        ADD      r0,r0,r0,LSL #1
        ADD      r0,r1,r0,LSL #1
        LDRB     r0,[r0,#0x203]
        BX       lr
        ENDP

getMinSpeedThreshold PROC
        LDR      r0,|L1.648|
        LDRB     r0,[r0,#0x27c]  ; radarInfo
        BX       lr
        ENDP

getAverageWindowTimeSecs PROC
        LDR      r0,|L1.648|
        LDR      r1,|L1.2016|
        LDR      r0,[r0,#0x280]  ; radarInfo
        UMULL    r2,r0,r1,r0
        LSL      r0,r0,#10
        LSR      r0,r0,#16
        BX       lr
        ENDP

getRadarOperatingStatus PROC
        LDR      r0,|L1.648|
        LDRB     r0,[r0,#0x284]  ; radarInfo
        ANDS     r0,r0,#1
        MOVNE    r0,#0x10
        BX       lr
        ENDP

getLastRadarReading PROC
        LDR      r0,|L1.812|
        LDR      r2,|L1.648|
        LDRH     r0,[r0,#0]  ; radarInfo
        MOV      r1,#0xab
        SUB      r0,r0,#1
        LSL      r0,r0,#23
        LSR      r0,r0,#23
|L1.2188|
        LDRB     r3,[r2,r0]
        CMP      r3,#0
        BNE      |L1.2228|
        SUBS     r1,r1,#1
        SUB      r0,r0,#1
        LSL      r0,r0,#23
        LSL      r1,r1,#16
        LSR      r0,r0,#23
        LSR      r1,r1,#16
        BCS      |L1.2188|
|L1.2228|
        LDRB     r0,[r2,r0]
        BX       lr
        ENDP

saveRadarZeroSpeed PROC
        PUSH     {r0,lr}
        LDRB     r0,[sp,#0]
        LDR      r1,|L1.648|
        MOV      r2,#1
        SUB      r0,r0,#1
        CMP      r0,#0xa
        MOVCS    r0,#3
        STRBCS   r0,[sp,#0]
        LDRB     r0,[sp,#0]
        STRB     r0,[r1,#0x27c]  ; radarInfo
        MOV      r1,sp
        MOV      r0,#0x25
        BL       writeFramData
        POP      {r3,lr}
        BX       lr
        ENDP

saveAverageWindowTime PROC
        MOV      r1,#0x3e8
        MUL      r0,r1,r0
        LDR      r2,|L1.652|
        SUB      r1,r0,#0x800
        SUB      r1,r1,#0x3b8
        CMP      r1,r2
        LDR      r1,|L1.648|
        MOVCS    r0,#0xa60
        ADDCS    r0,r0,#0xe000
        STR      r0,[r1,#0x280]!  ; radarInfo
        MOV      r2,#4
        MOV      r0,#0x26
        B        writeFramData
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

radarInfo
        %        648

        AREA ||.data||, DATA, ALIGN=2

packetError
        DCB      0x00,0x00,0x00,0x00
packetTimeStamp
        DCD      0x00000000

        EXPORT initRadar [CODE]
        EXPORT buildRxRadarPacket [CODE]
        EXPORT radarDoWork [CODE]
        EXPORT getAvgSpeed [CODE]
        EXPORT getTotalRadarReadings [CODE]
        EXPORT getNonZeroRadarReadings [CODE]
        EXPORT getOccupancyPercent [CODE]
        EXPORT getMinSpeedThreshold [CODE]
        EXPORT getAverageWindowTimeSecs [CODE]
        EXPORT getRadarOperatingStatus [CODE]
        EXPORT getLastRadarReading [CODE]
        EXPORT saveRadarZeroSpeed [CODE]
        EXPORT saveAverageWindowTime [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_memclr4 [CODE]
        IMPORT readFramData [CODE]
        IMPORT getTimeNow [CODE]
        IMPORT _printf_percent [CODE]
        IMPORT _printf_d [CODE]
        IMPORT _printf_int_dec [CODE]
        IMPORT __2printf [CODE]
        IMPORT _printf_x [CODE]
        IMPORT _printf_longlong_hex [CODE]
        IMPORT __aeabi_uidivmod [CODE]
        IMPORT hasTimedOut [CODE]
        IMPORT writeFramData [CODE]

        KEEP calcAvgSpeed
        KEEP radarInfo
        KEEP packetError
        KEEP packetTimeStamp

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,2
        ATTR SETVALUE Tag_ABI_optimization_goals,2
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
